### ISSUE TITLE
"dub build" failing

### ISSUE THREAD

**Issue by mi-ael** [w0rp/dsmoke#12]
$ dub build
Building dsmoke ~master configuration "library", build type debug.
Running dmd...
source/smoke/smoke_container.d(959): Error: pure function 'smoke.smoke_container.SmokeContainer.finalize.__foreachbody4.__foreachbody4' cannot call impure function 'smoke.smoke_container.namespaceForName'
source/smoke/smoke_container.d(1008): Error: pure function 'smoke.smoke_container.SmokeContainer.finalize.__foreachbody4.__foreachbody5' cannot call impure function 'smoke.smoke_container.namespaceForName'
source/smoke/smoke_generator.d(1423): Error: struct smoke.smoke_generator.SmokeGenerator is not copyable because it is annotated with @disable
source/smoke/smoke_loader.d(77): Error: no property 'setDefault' for type 'const(Method*)[][string]'
source/smoke/smoke_loader.d(291): Error: cannot modify const expression _strongMap[ptr]
source/smoke/smoke_loader.d(325): Error: no property 'setDefault' for type 'ClassLoader[string]'
source/smoke/smoke_loader.d(346): Error: struct smoke.smoke_loader.SmokeLoader is not copyable because it is annotated with @disable
FAIL .dub/build/library-debug-linux.posix-x86_64-dmd_2067-90E148395F717E9A7F9D11C8C198A6DA/ dsmoke staticLibrary
Error executing command build:
dmd failed with exit code 1.

**Comment by w0rp** [comment]
I'll have to update this and fix it. I mostly gave up on wrapping Qt
before, but the SMOKE stuff here might still be useful.

**Comment by mi-ael** [comment]
Cool, thanks!

**Comment by w0rp** [comment]
I just pushed another commit for the first time in a while, and the project should build again.

The SmokeGenerator and the SmokeLoader objects really shouldn't be copyable, as they are supposed to be unique objects which practically live forever in the program. Still, it had to make them copyable as an internal `cast(immutable)` in the library for returning them as immutable leads to calling the postblit for them, for some reason. It might be a DMD bug.

Let me know if this works for you. I could perhaps add some examples usages so you can figure out how to use this library. The related dqt library should give some clues.

**Comment by mi-ael** [comment]
thanks! I hope i can get DQT to work on my machine. This is a way better alternative to writing all the binding code myself...

**Comment by mi-ael** [comment]
And thanks again! I was able to build DQT without any problems
